------------------------------------------------------------------------------------POSTGRESQL---------------------------------------------------------------------------------------

CREATE TABLE COUNTRIES (
    COUNTRY_ID BIGINT,
    NAME CHARACTER VARYING(50) NOT NULL,
    CONSTRAINT COUNTRIES_PK PRIMARY KEY (COUNTRY_ID),
    CONSTRAINT COUNTRY_NAME_UNIQUE UNIQUE (NAME),
    CONSTRAINT COUNTRY_NAME_CHECK CHECK (LENGTH(NAME::TEXT) > 2)
);

CREATE SEQUENCE IF NOT EXISTS COUNTRIES_SEQUENCE AS BIGINT OWNED BY COUNTRIES.COUNTRY_ID;

ALTER TABLE COUNTRIES ALTER COLUMN COUNTRY_ID SET DEFAULT NEXTVAL('COUNTRIES_SEQUENCE');

CREATE TABLE HOTELS (
	HOTEL_ID BIGINT,
    NAME CHARACTER VARYING(50) NOT NULL,
    STARS SMALLINT NOT NULL,
    WEBSITE CHARACTER VARYING(255) NOT NULL,
    LATITUDE NUMERIC(9,7) NOT NULL,
	LONGITUDE NUMERIC(10,7) NOT NULL,
    CONSTRAINT HOTELS_PK PRIMARY KEY (HOTEL_ID),
    CONSTRAINT HOTEL_NAME_UNIQUE UNIQUE (NAME),
	CONSTRAINT HOTEL_NAME_CHECK CHECK (LENGTH(NAME::TEXT) > 3),
	CONSTRAINT HOTEL_STARS_CHECK CHECK (STARS > 0 AND STARS < 6),
    CONSTRAINT HOTEL_WEBSITE_REGEX_CHECK CHECK (WEBSITE::TEXT ~ 'http[s]?\:\/\/www\.\w+\.[a-z]{2,3}($|\/[\w\/\-]+\/$)'::TEXT),
	CONSTRAINT HOTEL_LATITUDE_CHECK CHECK (LATITUDE > -90.000000 AND LATITUDE < 90.000000),
	CONSTRAINT HOTEL_LONGITUDE_CHECK CHECK (LONGITUDE > -180.000000 AND LONGITUDE < 180.000000)
);

CREATE SEQUENCE IF NOT EXISTS HOTELS_SEQUENCE AS BIGINT OWNED BY HOTELS.HOTEL_ID;

ALTER TABLE HOTELS ALTER COLUMN HOTEL_ID SET DEFAULT NEXTVAL('HOTELS_SEQUENCE');

CREATE TABLE FEATURES (
	FEATURE_ID BIGINT,
	NAME CHARACTER VARYING(30) NOT NULL,
	CONSTRAINT FEATURES_PK PRIMARY KEY (FEATURE_ID),
    CONSTRAINT FEATURE_NAME_UNIQUE UNIQUE (NAME),
	CONSTRAINT FEATURE_NAME_CHECK CHECK (LENGTH(NAME::TEXT) > 3)
);

CREATE SEQUENCE IF NOT EXISTS FEATURES_SEQUENCE AS BIGINT OWNED BY FEATURES.FEATURE_ID;

ALTER TABLE FEATURES ALTER COLUMN FEATURE_ID SET DEFAULT NEXTVAL('FEATURES_SEQUENCE');

CREATE TABLE HOTELS_FEATURES (
	HOTEL_ID BIGINT NOT NULL,
	FEATURE_ID BIGINT NOT NULL,
	CONSTRAINT HOTELS_FEATURES_PK PRIMARY KEY(HOTEL_ID, FEATURE_ID),
	CONSTRAINT HOTELS_FEATURES_HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS (HOTEL_ID),
	CONSTRAINT HOTELS_FEATURES_FEATURE_ID_FK FOREIGN KEY (FEATURE_ID) REFERENCES FEATURES (FEATURE_ID)
);

CREATE TABLE USERS (
    USER_ID BIGINT,
    LOGIN CHARACTER VARYING(30) NOT NULL,
    PASSWORD CHARACTER VARYING(30) NOT NULL,
	ROLE CHARACTER VARYING(10) DEFAULT 'USER',
    CONSTRAINT USERS_PKEY PRIMARY KEY (USER_ID),
    CONSTRAINT USER_LOGIN_UNIQUE UNIQUE (LOGIN),
    CONSTRAINT USER_LOGIN_CHECK CHECK (LENGTH(LOGIN::TEXT) > 4),
    CONSTRAINT USER_PASSWORD_CHECK CHECK (LENGTH(PASSWORD::TEXT) > 4),
	CONSTRAINT USER_ROLE_CHECK CHECK (LENGTH(ROLE) > 3 AND ROLE IN ('USER', 'ADMIN'))
);

CREATE SEQUENCE IF NOT EXISTS USERS_SEQUENCE AS BIGINT OWNED BY USERS.USER_ID;

ALTER TABLE USERS ALTER COLUMN USER_ID SET DEFAULT NEXTVAL('USERS_SEQUENCE');

CREATE TABLE TOURS (
    TOUR_ID BIGINT,
    PHOTO_PATH CHARACTER VARYING(255),
    START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    DESCRIPTION TEXT,
    COST NUMERIC(14,4) NOT NULL,
    TOUR_TYPE CHARACTER VARYING(255),
    HOTEL_ID BIGINT,
    COUNTRY_ID BIGINT,
    CONSTRAINT TOURS_PK PRIMARY KEY (TOUR_ID),
    CONSTRAINT TOURS_COUNTRY_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID),
    CONSTRAINT TOURS_HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS (HOTEL_ID),
    CONSTRAINT TOUR_COST_CHECK CHECK (COST > 0.0000),
    CONSTRAINT TOUR_END_DATE_CHECK CHECK (AGE(END_DATE, START_DATE) > '1 DAY'::INTERVAL),
    CONSTRAINT TOUR_START_DATE_CHECK CHECK (START_DATE >= NOW()),
	CONSTRAINT TOUR_TYPE_CHECK CHECK (TOUR_TYPE IN ('TREATMENT', 'TOURISM', 'LEISURE', 'BUSINESS',
	'PILGRIMAGE','TRAINING', 'SPORT_COMPETITION', 'RURAL_TOURISM', 'SCIENTIFIC_EXPEDITION', 'ECOTOURISM'))
);

CREATE SEQUENCE IF NOT EXISTS TOURS_SEQUENCE AS BIGINT OWNED BY TOURS.TOUR_ID;

ALTER TABLE TOURS ALTER COLUMN TOUR_ID SET DEFAULT NEXTVAL('TOURS_SEQUENCE');

CREATE TABLE USERS_TOURS (
    USER_ID BIGINT NOT NULL,
    TOUR_ID BIGINT NOT NULL,
    CONSTRAINT USERS_TOURS_PK PRIMARY KEY (USER_ID, TOUR_ID),
    CONSTRAINT USERS_TOURS_TOUR_ID_FK FOREIGN KEY (TOUR_ID) REFERENCES TOURS (TOUR_ID),
    CONSTRAINT USERS_TOURS_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE REVIEWS (
    REVIEW_ID BIGINT,
    REVIEW_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    REVIEW_TEXT CHARACTER VARYING(255) NOT NULL,
    USER_ID BIGINT,
    TOUR_ID BIGINT,
    CONSTRAINT REVIEWS_PK PRIMARY KEY (REVIEW_ID),
    CONSTRAINT REVIEWS_TOUR_ID_FK FOREIGN KEY (TOUR_ID) REFERENCES TOURS (TOUR_ID),
    CONSTRAINT REVIEWS_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT REVIEW_DATE_CHECK CHECK (REVIEW_DATE >= NOW())
);

CREATE SEQUENCE IF NOT EXISTS REVIEWS_SEQUENCE AS BIGINT OWNED BY REVIEWS.REVIEW_ID;

ALTER TABLE REVIEWS ALTER COLUMN REVIEW_ID SET DEFAULT NEXTVAL('REVIEWS_SEQUENCE');